name: Create Zip Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build a zip of the plugin files
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.7.6
      with:
        filename: 'simplecal.zip'
        path: 'simplecal'
        exclusions: '/*node_modules/* src .editorconfig  *.git* package-lock.json package.json'
